//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IEmployeeService")]
    public interface IEmployeeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/saveUser", ReplyAction="http://tempuri.org/IEmployeeService/saveUserResponse")]
        string saveUser(string fn, string ln, string mobile_no, string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/saveUser", ReplyAction="http://tempuri.org/IEmployeeService/saveUserResponse")]
        System.Threading.Tasks.Task<string> saveUserAsync(string fn, string ln, string mobile_no, string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/login", ReplyAction="http://tempuri.org/IEmployeeService/loginResponse")]
        string login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/login", ReplyAction="http://tempuri.org/IEmployeeService/loginResponse")]
        System.Threading.Tasks.Task<string> loginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/getName", ReplyAction="http://tempuri.org/IEmployeeService/getNameResponse")]
        string getName(int uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/getName", ReplyAction="http://tempuri.org/IEmployeeService/getNameResponse")]
        System.Threading.Tasks.Task<string> getNameAsync(int uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/addInncome", ReplyAction="http://tempuri.org/IEmployeeService/addInncomeResponse")]
        System.Data.DataSet addInncome();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/addInncome", ReplyAction="http://tempuri.org/IEmployeeService/addInncomeResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> addInncomeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/addExpense", ReplyAction="http://tempuri.org/IEmployeeService/addExpenseResponse")]
        System.Data.DataSet addExpense();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/addExpense", ReplyAction="http://tempuri.org/IEmployeeService/addExpenseResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> addExpenseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/addOwnIncomeCategory", ReplyAction="http://tempuri.org/IEmployeeService/addOwnIncomeCategoryResponse")]
        string addOwnIncomeCategory(int uid, string cat_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/addOwnIncomeCategory", ReplyAction="http://tempuri.org/IEmployeeService/addOwnIncomeCategoryResponse")]
        System.Threading.Tasks.Task<string> addOwnIncomeCategoryAsync(int uid, string cat_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/getOwnIncomeCategory", ReplyAction="http://tempuri.org/IEmployeeService/getOwnIncomeCategoryResponse")]
        System.Data.DataSet getOwnIncomeCategory(int uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/getOwnIncomeCategory", ReplyAction="http://tempuri.org/IEmployeeService/getOwnIncomeCategoryResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> getOwnIncomeCategoryAsync(int uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/addTransaction", ReplyAction="http://tempuri.org/IEmployeeService/addTransactionResponse")]
        string addTransaction(int income, string cat, int uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/addTransaction", ReplyAction="http://tempuri.org/IEmployeeService/addTransactionResponse")]
        System.Threading.Tasks.Task<string> addTransactionAsync(int income, string cat, int uid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeeServiceChannel : EmployeeClient.ServiceReference1.IEmployeeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeServiceClient : System.ServiceModel.ClientBase<EmployeeClient.ServiceReference1.IEmployeeService>, EmployeeClient.ServiceReference1.IEmployeeService {
        
        public EmployeeServiceClient() {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string saveUser(string fn, string ln, string mobile_no, string email, string password) {
            return base.Channel.saveUser(fn, ln, mobile_no, email, password);
        }
        
        public System.Threading.Tasks.Task<string> saveUserAsync(string fn, string ln, string mobile_no, string email, string password) {
            return base.Channel.saveUserAsync(fn, ln, mobile_no, email, password);
        }
        
        public string login(string username, string password) {
            return base.Channel.login(username, password);
        }
        
        public System.Threading.Tasks.Task<string> loginAsync(string username, string password) {
            return base.Channel.loginAsync(username, password);
        }
        
        public string getName(int uid) {
            return base.Channel.getName(uid);
        }
        
        public System.Threading.Tasks.Task<string> getNameAsync(int uid) {
            return base.Channel.getNameAsync(uid);
        }
        
        public System.Data.DataSet addInncome() {
            return base.Channel.addInncome();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> addInncomeAsync() {
            return base.Channel.addInncomeAsync();
        }
        
        public System.Data.DataSet addExpense() {
            return base.Channel.addExpense();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> addExpenseAsync() {
            return base.Channel.addExpenseAsync();
        }
        
        public string addOwnIncomeCategory(int uid, string cat_name) {
            return base.Channel.addOwnIncomeCategory(uid, cat_name);
        }
        
        public System.Threading.Tasks.Task<string> addOwnIncomeCategoryAsync(int uid, string cat_name) {
            return base.Channel.addOwnIncomeCategoryAsync(uid, cat_name);
        }
        
        public System.Data.DataSet getOwnIncomeCategory(int uid) {
            return base.Channel.getOwnIncomeCategory(uid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getOwnIncomeCategoryAsync(int uid) {
            return base.Channel.getOwnIncomeCategoryAsync(uid);
        }
        
        public string addTransaction(int income, string cat, int uid) {
            return base.Channel.addTransaction(income, cat, uid);
        }
        
        public System.Threading.Tasks.Task<string> addTransactionAsync(int income, string cat, int uid) {
            return base.Channel.addTransactionAsync(income, cat, uid);
        }
    }
}
